In [2]:
import tensorflow as tf
import numpy as np

### 1. Show and Save Data Flow Graph

In [4]:
g = tf.Graph()
with g.as_default():
    sess = tf.Session()
    W = tf.Variable(tf.zeros(shape=[10, 5]))
    x = tf.placeholder(dtype=tf.float32, shape=[None, 10])
    result = tf.matmul(x, W)
    ## writer = tf.summary.FileWriter("/Users/lixing/board/chap01", g)
    ## writer.close()
    ### exec tensorboard --logdir=/Users/lixing/board/chap01 on terminal
    print(g.as_graph_def())

node {
  name: "zeros"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 10
          }
          dim {
            size: 5
          }
        }
        float_val: 0.0
      }
    }
  }
}
node {
  name: "Variable"
  op: "VariableV2"
  attr {
    key: "container"
    value {
      s: ""
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 10
        }
        dim {
          size: 5
        }
      }
    }
  }
  attr {
    key: "shared_name"
    value {
      s: ""
    }
  }
}
node {
  name: "Variable/Assign"
  op: "Assign"
  input: "Variable"
  input: "zeros"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@Variable"
      }
    }


### 2. Simple Matrix Calculations

In [11]:
sess = tf.InteractiveSession()
## int32 4*4 matrix
X = tf.constant([[2, 5, 3, -5], 
                 [0, 3, -2, 5], 
                 [4, 3, 5, 3], 
                 [6, 1, 4, 0]])
## int32 4*5 matrix
Y = tf.constant([[4, -7, 4, -3, 4], 
                 [6, 4, -7, 4, 7], 
                 [2, 3, 2, 1, 4], 
                 [1, 5, 5, 5, 2]])

In [21]:
## change dtype of a tensor
floatX = tf.cast(X, tf.float32)

In [23]:
tf.transpose(X).eval()

array([[ 2,  0,  4,  6],
       [ 5,  3,  3,  1],
       [ 3, -2,  5,  4],
       [-5,  5,  3,  0]], dtype=int32)

In [25]:
## 矩阵乘法
tf.matmul(X, Y).eval()
## same as (X @ Y).eval()

array([[ 39, -10, -46,  -8,  45],
       [ 19,  31,   0,  35,  23],
       [ 47,  14,  20,  20,  63],
       [ 38, -26,  25, -10,  47]], dtype=int32)

In [29]:
## 矩阵行列式
tf.matrix_determinant(floatX).eval()

817.9997

In [33]:
## 矩阵的逆
tf.matrix_inverse(floatX).eval()

array([[-0.00855745,  0.10513447, -0.18948655,  0.29584354],
       [ 0.12958434,  0.12224938,  0.01222495, -0.05134475],
       [-0.01955992, -0.18826404,  0.2811736 , -0.1809291 ],
       [-0.08557458,  0.05134474,  0.10513448, -0.0415648 ]],
      dtype=float32)

In [32]:
(tf.matrix_inverse(floatX) @ floatX).eval()

array([[ 1.0000002e+00,  8.9406967e-08,  1.1920929e-07,  0.0000000e+00],
       [-2.9802322e-08,  1.0000000e+00,  0.0000000e+00,  4.4703484e-08],
       [-1.1920929e-07, -8.9406967e-08,  9.9999988e-01,  1.7881393e-07],
       [-2.9802322e-08, -3.3527613e-08, -4.4703484e-08,  1.0000000e+00]],
      dtype=float32)

In [35]:
## 解线性方程组
rhs = [[1], [1], [1], [1]]
tf.matrix_solve(floatX, rhs).eval()

array([[ 0.202934  ],
       [ 0.21271393],
       [-0.10757945],
       [ 0.02933985]], dtype=float32)

### 3. 约减（Reduction）

In [39]:
# int32 3*3 matrix
X = tf.constant([[1, 2, 3], 
                 [3, 2, 1], 
                 [-1, -2, -3]])
# bool 3*3 matrix
boolean_tensor = tf.constant([[True, False, True], 
                              [False, False, True], 
                              [True, False, False]])

In [41]:
tf.reduce_prod(X, axis=1).eval()

array([ 6,  6, -6], dtype=int32)

In [42]:
tf.reduce_prod(X, axis=0).eval()

array([-3, -8, -9], dtype=int32)

In [45]:
tf.reduce_min(X, axis=1).eval()

array([ 1,  1, -3], dtype=int32)

In [47]:
tf.reduce_all(boolean_tensor, axis=1).eval()

array([False, False, False])

In [50]:
tf.reduce_any(boolean_tensor, axis=0).eval()

array([ True, False,  True])

### 4. 分割（segment）

In [60]:
tens1 = tf.constant([[2, 5, 3, -5], 
                     [0, 3, -2, 5], 
                     [4, 3, 5, 3], 
                     [6, 1, 4, 0], 
                     [6, 1, 4, 0]])
## segment ids 给出的是组号，也是最后输出对应的行号，长度一定与tens1的行数相等
## segment ids must be increasing

In [61]:
seg_ids = tf.constant([0, 1, 1, 4, 4])
tf.segment_sum(tens1, seg_ids).eval()

array([[ 2,  5,  3, -5],
       [ 4,  6,  3,  8],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [12,  2,  8,  0]], dtype=int32)

In [62]:
seg_ids = tf.constant([0, 1, 1, 2, 2])
tf.segment_sum(tens1, seg_ids).eval()

array([[ 2,  5,  3, -5],
       [ 4,  6,  3,  8],
       [12,  2,  8,  0]], dtype=int32)

In [63]:
seg_ids = tf.constant([0, 1, 1, 2, 2])
tf.segment_mean(tens1, seg_ids).eval()

array([[ 2,  5,  3, -5],
       [ 2,  3,  1,  4],
       [ 6,  1,  4,  0]], dtype=int32)

In [65]:
seg_ids = tf.constant([0, 1, 1, 2, 2])
tf.segment_max(tens1, seg_ids).eval()

array([[ 2,  5,  3, -5],
       [ 4,  3,  5,  5],
       [ 6,  1,  4,  0]], dtype=int32)

### 5. 序列

In [82]:
x = tf.constant([[2, 5, 3, -5], 
                 [0, 3, -2, 5], 
                 [4, 3, 5, 3], 
                 [6, 1, 4, 0]])
listx = tf.constant(np.arange(1, 9), dtype=tf.int32)
listy = tf.constant([4, 5, 8, 9], dtype=tf.int32)
boolx = tf.constant([[True, False], [False, True]])

In [80]:
tf.argmin(x, axis=1).eval()

array([3, 2, 1, 3])

In [93]:
diff_elements, diff_indexes_of_x = tf.setdiff1d(listx, listy)
print(diff_elements.eval())
print(diff_indexes_of_x.eval())

[1 2 3 6 7]
[0 1 2 5 6]


In [96]:
tf.where(x > 3).eval()

array([[0, 1],
       [1, 3],
       [2, 0],
       [2, 2],
       [3, 0],
       [3, 2]])

In [98]:
tf.where(boolx).eval()

array([[0, 0],
       [1, 1]])

In [102]:
elements, indexes = tf.unique(listx)
print(elements.eval())
print(indexes.eval())

[1 2 3 4 5 6 7 8]
[0 1 2 3 4 5 6 7]


### 6. 形状变换  切片 连接 填充 打包

In [103]:
x = tf.constant([[2, 5, 3, -5], 
                 [0, 3, -2, 5], 
                 [4, 3, 5, 3], 
                 [6, 1, 4, 0]])

In [107]:
tf.shape(x).eval()
## x.shape.as_list()

array([4, 4], dtype=int32)

In [111]:
tf.size(x).eval()

16

In [114]:
tf.rank(x).eval()

2

In [117]:
tf.reshape(x, [8, 2]).eval()

array([[ 2,  5],
       [ 3, -5],
       [ 0,  3],
       [-2,  5],
       [ 4,  3],
       [ 5,  3],
       [ 6,  1],
       [ 4,  0]], dtype=int32)

In [128]:
a = tf.constant([[0,1,2,3]])
print(a.eval())
print(tf.squeeze(a).eval())

[[0 1 2 3]]
[0 1 2 3]


In [130]:
tf.expand_dims(x, axis=1).eval()

array([[[ 2,  5,  3, -5]],

       [[ 0,  3, -2,  5]],

       [[ 4,  3,  5,  3]],

       [[ 6,  1,  4,  0]]], dtype=int32)

In [134]:
# [[1 2 3]
# [4 5 6]
# [7 8 9]]
t_matrix = tf.reshape(tf.constant(np.arange(1, 10)), [3, 3])
t_array = tf.constant([1, 2, 3, 4, 9, 8, 6, 5])
t_array2 = tf.constant([2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
tf.slice(t_matrix, begin=[1, 1], size=[2, 2]).eval()

array([[5, 6],
       [8, 9]])

In [144]:
t1, t2 = tf.split(t_array, 2)  ## split 必须是等分
print(t1.eval())
print(t2.eval())

[1 2 3 4]
[9 8 6 5]


In [148]:
tf.tile([1, 2], [3]).eval()

array([1, 2, 1, 2, 1, 2], dtype=int32)

In [156]:
tf.pad(t_matrix, paddings=[[1, 2], [0, 1]]).eval()

array([[0, 0, 0, 0],
       [1, 2, 3, 0],
       [4, 5, 6, 0],
       [7, 8, 9, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [168]:
print(tf.concat([t_array, t_array2], axis=0).eval())
print(tf.concat([tf.reshape(t_array, [1, -1]), tf.reshape(t_array2, [1, -1])], axis=0).eval())

[1 2 3 4 9 8 6 5 2 3 4 5 6 7 8 9]
[[1 2 3 4 9 8 6 5]
 [2 3 4 5 6 7 8 9]]


In [166]:
print(tf.stack([t_array, t_array2], axis=0).eval())
print(tf.stack([t_array, t_array2], axis=1).eval())

[[1 2 3 4 9 8 6 5]
 [2 3 4 5 6 7 8 9]]
[[1 2]
 [2 3]
 [3 4]
 [4 5]
 [9 6]
 [8 7]
 [6 8]
 [5 9]]


In [172]:
print(sess.run(tf.unstack(t_matrix, axis=0)))
print(sess.run(tf.unstack(t_matrix, axis=1)))

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[array([1, 4, 7]), array([2, 5, 8]), array([3, 6, 9])]


In [195]:
tf.reverse(t_matrix, axis=tf.constant([1])).eval()

array([[3, 2, 1],
       [6, 5, 4],
       [9, 8, 7]])

In [185]:
tf.reverse(t_matrix, axis=tf.constant([0])).eval()

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [194]:
tf.reverse(t_matrix, axis=tf.constant([0, 1])).eval()

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

### 7. 数据读取

In [12]:
## csv
file_path = "/Users/lixing/jupyter/Build ML Projects with TF/Chap01_bak/iris.csv"

In [9]:
def read_data(file_queue):
    reader = tf.TextLineReader(skip_header_lines=1)
    key, value = reader.read(file_queue)
    record_defaults = [[''], [''], [''], [''], ['']]
    SepalLength, SepalWidth, PetalLength, PetalWidth, Species = tf.decode_csv(value, record_defaults)
    process_op = tf.case({
        tf.equal(Species, tf.constant("setosa")): lambda : tf.constant(1), 
        tf.equal(Species, tf.constant("versicolor")): lambda : tf.constant(2), 
        tf.equal(Species, tf.constant("virginica")): lambda : tf.constant(3)}, 
        default=lambda : tf.constant(-1), exclusive=True)
    dat = tf.stack([SepalLength, SepalWidth, PetalLength, PetalWidth, Species], axis=0)
    return dat, process_op

def create_pipeline(file_path, batch_size, num_epochs=None):
    file_queue = tf.train.string_input_producer(
        tf.train.match_filenames_once(file_path), 
        shuffle=True,
        num_epochs=num_epochs)
    example, label = read_data(file_queue)
    min_after_dequeue = 1000
    capacity = min_after_dequeue + batch_size
    example_batch, label_batch = tf.train.shuffle_batch(
        [example, label], 
        batch_size=batch_size, 
        capacity=capacity,
        min_after_dequeue=min_after_dequeue)
    return example_batch, label_batch
    

In [13]:
x_test, y_test = create_pipeline(file_path, 60)

In [14]:
init_op = tf.global_variables_initializer()
local_init_op = tf.local_variables_initializer()

with tf.Session() as sess:
    sess.run(init_op)
    sess.run(local_init_op)
    coord = tf.train.Coordinator()
    threads = tf.train.start_queue_runners(coord=coord)
    try:
        for _ in range(6):
            example, label = sess.run([x_test, y_test])
            print (example)
            print (label)
    except tf.errors.OutOfRangeError:
        print ('Done reading')
    finally:
        coord.request_stop()
        coord.join(threads)
        sess.close()
    

[[b'5.8' b'2.7' b'3.9' b'1.2' b'versicolor']
 [b'5.6' b'3' b'4.5' b'1.5' b'versicolor']
 [b'5.6' b'2.7' b'4.2' b'1.3' b'versicolor']
 [b'5.7' b'4.4' b'1.5' b'0.4' b'setosa']
 [b'4.4' b'2.9' b'1.4' b'0.2' b'setosa']
 [b'4.8' b'3' b'1.4' b'0.3' b'setosa']
 [b'5.7' b'3.8' b'1.7' b'0.3' b'setosa']
 [b'5.7' b'2.9' b'4.2' b'1.3' b'versicolor']
 [b'4.8' b'3.4' b'1.6' b'0.2' b'setosa']
 [b'7.2' b'3.2' b'6' b'1.8' b'virginica']
 [b'5.1' b'3.5' b'1.4' b'0.3' b'setosa']
 [b'6.4' b'3.2' b'4.5' b'1.5' b'versicolor']
 [b'6.4' b'2.9' b'4.3' b'1.3' b'versicolor']
 [b'4.8' b'3' b'1.4' b'0.3' b'setosa']
 [b'6.5' b'3' b'5.2' b'2' b'virginica']
 [b'5.1' b'3.5' b'1.4' b'0.3' b'setosa']
 [b'5.1' b'3.7' b'1.5' b'0.4' b'setosa']
 [b'6.4' b'2.8' b'5.6' b'2.2' b'virginica']
 [b'6.7' b'3' b'5.2' b'2.3' b'virginica']
 [b'5' b'2.3' b'3.3' b'1' b'versicolor']
 [b'5.7' b'2.6' b'3.5' b'1' b'versicolor']
 [b'5.6' b'3' b'4.5' b'1.5' b'versicolor']
 [b'5.7' b'3' b'4.2' b'1.2' b'versicolor']
 [b'6.5' b'2.8' b'4.6' b'1.5'

In [3]:
## picture
import matplotlib.pyplot as plt
path = "/Users/lixing/jupyter/Build ML Projects with TF/Chap01_bak/"
file_path = path + "00.jpg"

In [4]:
filename_queue = tf.train.string_input_producer(
    tf.train.match_filenames_once(file_path))

In [5]:
reader = tf.WholeFileReader()
key, value = reader.read(filename_queue)
image = tf.image.decode_jpeg(value)

flipImageUpDown = tf.image.flip_up_down(image)
flipImageLeftRight = tf.image.flip_left_right(image)

init_op = tf.global_variables_initializer()
local_init_op = tf.local_variables_initializer()

In [7]:
with tf.Session() as sess:
    try:
        sess.run(init_op)
        sess.run(local_init_op)
        coord = tf.train.Coordinator()
        threads = tf.train.start_queue_runners(coord=coord, sess=sess)
        up_down_image = tf.image.encode_jpeg(flipImageUpDown)
        left_right_image = tf.image.encode_jpeg(flipImageLeftRight)
        example = sess.run(flipImageLeftRight)
        print(example)  ## 逐行 RGB值
        
    except tf.errors.OutOfRangeError:
        print ('Done reading')
    finally:
        f = open(path + "left_right.jpg", "wb+")
        f.write(left_right_image.eval(session=sess))
        f.close()
        
        f = open(path + "up_down_image.jpg", "wb+")
        f.write(up_down_image.eval(session=sess))
        f.close()
        #plt.imshow(flipImageLeftRight.eval(session=sess))
        #plt.imshow(flipImageUpDown.eval(session=sess))
        coord.request_stop()
        coord.join(threads)
        sess.close()

[[[234 254 253]
  [234 254 253]
  [234 254 253]
  ...
  [  7  28  11]
  [  8  36  11]
  [  0  35   5]]

 [[234 254 253]
  [234 254 253]
  [234 254 253]
  ...
  [  0  18   0]
  [  0  26   1]
  [  0  25   0]]

 [[234 254 253]
  [234 254 253]
  [234 254 253]
  ...
  [  2  19   1]
  [  1  25   3]
  [  0  25   0]]

 ...

 [[251 253 252]
  [252 252 252]
  [254 254 252]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[252 254 253]
  [254 255 255]
  [254 255 255]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]

 [[254 255 255]
  [251 253 252]
  [252 254 253]
  ...
  [254 254 254]
  [254 254 254]
  [254 254 254]]]
